name: Run MailingBot on Schedule

on:
  schedule:
    - cron: "0 5 1 * *" # “At 05:00 on day-of-month 1.”

  workflow_dispatch:

jobs:
  run-mailingbot:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - 
        name: Run MailingBot Docker Container
        run: |
          docker pull seblum/mailingbot:latest
          docker run --rm --volume $(pwd)/src/data/:/src/data/ \
          -e EMAIL_SENDER="${{ secrets.EMAIL_SENDER }}" \
          -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
          -e EMAIL_RECEIVER="${{ secrets.EMAIL_RECEIVER }}" \
          -e HTML_PATH="${{ secrets.HTML_PATH }}" \
          seblum/mailingbot:latest
