name: Run MailingBot on Schedule

# This workflow runs on a schedule (every day at midnight UTC in this example)
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-mailingbot:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      - 
        name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - 
        name: Run MailingBot Docker Container
        run: |
          echo "Running from $(pwd)"
          docker pull seblum/mailingbot:latest
          docker run --rm --volume $(pwd)/src/data/:/src/data/ \
          seblum/mailingbot:latest
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          HTML_PATH: ${{ secrets.HTML_PATH }}
            # -e EMAIL_SENDER="${{ secrets.EMAIL_SENDER }}" \
            # -e EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            # -e EMAIL_RECEIVER="${{ secrets.EMAIL_RECEIVER }}" \
            # -e HTML_PATH="${{ secrets.HTML_PATH }}" \
